language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "10"
install:
  - npm install -g yarn
  - yarn install
script:
  - yarn lint
notifications:
  email:
    on_success: never
after_success:
  - codeclimate-test-reporter < ./test/unit/coverage/lcov.info
